### ISSUE TITLE
Random failure in blackbox test

### ISSUE THREAD

**Issue by pfrenssen** [jhedstrom/drupalextension#204]
We sometimes get random failures in the blackbox test. For example this happened in [build 854.5](https://travis-ci.org/jhedstrom/drupalextension/jobs/77353711):

```
When I click "Commits" #features/blackbox.feature:86
      exception 'Behat\Mink\Exception\DriverException' with message 'Error while processing event 'click'' in vendor/behat/mink-zombie-driver/src/Behat/Mink/Driver/ZombieDriver.php:861
      Stack trace:
      #0 vendor/behat/mink-zombie-driver/src/Behat/Mink/Driver/ZombieDriver.php(693): Behat\Mink\Driver\ZombieDriver->triggerBrowserEvent('click', '(//html/.//a\n[....')
      #1 vendor/behat/mink/src/Element/NodeElement.php(153): Behat\Mink\Driver\ZombieDriver->click('(//html/.//a\n[....')
      #2 vendor/behat/mink/src/Element/TraversableElement.php(77): Behat\Mink\Element\NodeElement->click()
      #3 vendor/behat/mink-extension/src/Behat/MinkExtension/Context/MinkContext.php(95): Behat\Mink\Element\TraversableElement->clickLink('Commits')
      #4 src/Drupal/DrupalExtension/Context/MinkContext.php(70): Behat\MinkExtension\Context\MinkContext->clickLink('Commits')
      #5 [internal function]: Drupal\DrupalExtension\Context\MinkContext->assertClick('Commits')
      ...
```

What could be the cause of this? This is using http://drupal.org/ to run the tests. Could it be a connectivity problem?

**Comment by jhedstrom** [comment]
I think so. Long term we could look at simply serving some local static files in travis instead of hitting d.o.

I just opened #203 because I realized these hadn't been running.

**Comment by pfrenssen** [comment]
Closing this as a duplicate of #310.
