### ISSUE TITLE
Failed to log in as user

### ISSUE THREAD

**Issue by kostajh** [jhedstrom/drupalextension#245]
I'm running into a weird situation (I'm on Drupal Extension v3.1.5) and wonder if anyone's encountered this so far.

In my VM (based on Drupal VM), I can run the `Given I am logged in as a user with the "authenticated user" role` without error, using Goutte or Selenium2. On a remote dev server, I can run that step with Selenium2, but it fails with Goutte. Here's the error and stacktrace:

```
Given I am logged in as a user with the "authenticated user" role # Drupal\DrupalExtension\Context\DrupalContext::assertAuthenticatedByRole()
      exception 'Exception' with message 'Failed to log in as user 'auPEurd0' with role 'authenticated user'' in /var/lib/jenkins/workspace/example-tests/vendor/drupal/drupal-extension/src/Drupal/DrupalExtension/Context/RawDrupalContext.php:430
      Stack trace:
      #0 /var/lib/jenkins/workspace/example-tests/vendor/drupal/drupal-extension/src/Drupal/DrupalExtension/Context/DrupalContext.php(64): Drupal\DrupalExtension\Context\RawDrupalContext->login()
      #1 [internal function]: Drupal\DrupalExtension\Context\DrupalContext->assertAuthenticatedByRole('authenticated u...')
      #2 /var/lib/jenkins/workspace/example-tests/vendor/behat/behat/src/Behat/Testwork/Call/Handler/RuntimeCallHandler.php(99): call_user_func_array(Array, Array)
      #3 /var/lib/jenkins/workspace/example-tests/vendor/behat/behat/src/Behat/Testwork/Call/Handler/RuntimeCallHandler.php(54): Behat\Testwork\Call\Handler\RuntimeCallHandler->executeCall(Object(Behat\Behat\Definition\Call\DefinitionCall))
      #4 /var/lib/jenkins/workspace/example-tests/vendor/behat/behat/src/Behat/Testwork/Call/CallCenter.php(125): Behat\Testwork\Call\Handler\RuntimeCallHandler->handleCall(Object(Behat\Behat\Definition\Call\DefinitionCall))
      #5 /var/lib/jenkins/workspace/example-tests/vendor/behat/behat/src/Behat/Testwork/Call/CallCenter.php(80): Behat\Testwork\Call\CallCenter->handleCall(Object(Behat\Behat\Definition\Call\DefinitionCall))
      #6 /var/lib/jenkins/workspace/example-tests/vendor/behat/behat/src/Behat/Behat/Tester/Runtime/RuntimeStepTester.php(125): Behat\Testwork\Call\CallCenter->makeCall(Object(Behat\Behat\Definition\Call\DefinitionCall))
      #7 /var/lib/jenkins/workspace/example-tests/vendor/behat/behat/src/Behat/Behat/Tester/Runtime/RuntimeStepTester.php(73): Behat\Behat\Tester\Runtime\RuntimeStepTester->testDefinition(Object(Behat\Behat\Context\Environment\InitializedContextEnvironment), Object(Behat\Gherkin\Node\FeatureNode), Object(Behat\Gherkin\Node\StepNode), Object(Behat\Behat\Definition\SearchResult), false)
      #8 /var/lib/jenkins/workspace/example-tests/vendor/behat/behat/src/Behat/Behat/Hook/Tester/HookableStepTester.php(74): Behat\Behat\Tester\Runtime\RuntimeStepTester->test(Object(Behat\Behat\Context\Environment\InitializedContextEnvironment), Object(Behat\Gherkin\Node\FeatureNode), Object(Behat\Gherkin\Node\StepNode), false)
      #9 /var/lib/jenkins/workspace/example-tests/vendor/behat/behat/src/Behat/Behat/EventDispatcher/Tester/EventDispatchingStepTester.php(73): Behat\Behat\Hook\Tester\HookableStepTester->test(Object(Behat\Behat\Context\Environment\InitializedContextEnvironment), Object(Behat\Gherkin\Node\FeatureNode), Object(Behat\Gherkin\Node\StepNode), false)
      #10 /var/lib/jenkins/workspace/example-tests/vendor/behat/behat/src/Behat/Behat/Tester/StepContainerTester.php(59): Behat\Behat\EventDispatcher\Tester\EventDispatchingStepTester->test(Object(Behat\Behat\Context\Environment\InitializedContextEnvironment), Object(Behat\Gherkin\Node\FeatureNode), Object(Behat\Gherkin\Node\StepNode), false)
      #11 /var/lib/jenkins/workspace/example-tests/vendor/behat/behat/src/Behat/Behat/Tester/Runtime/RuntimeScenarioTester.php(76): Behat\Behat\Tester\StepContainerTester->test(Object(Behat\Behat\Context\Environment\InitializedContextEnvironment), Object(Behat\Gherkin\Node\FeatureNode), Object(Behat\Gherkin\Node\ScenarioNode), false)
      #12 /var/lib/jenkins/workspace/example-tests/vendor/behat/behat/src/Behat/Behat/Hook/Tester/HookableScenarioTester.php(74): Behat\Behat\Tester\Runtime\RuntimeScenarioTester->test(Object(Behat\Behat\Context\Environment\InitializedContextEnvironment), Object(Behat\Gherkin\Node\FeatureNode), Object(Behat\Gherkin\Node\ScenarioNode), false)
      #13 /var/lib/jenkins/workspace/example-tests/vendor/behat/behat/src/Behat/Behat/EventDispatcher/Tester/EventDispatchingScenarioTester.php(103): Behat\Behat\Hook\Tester\HookableScenarioTester->test(Object(Behat\Behat\Context\Environment\InitializedContextEnvironment), Object(Behat\Gherkin\Node\FeatureNode), Object(Behat\Gherkin\Node\ScenarioNode), false)
      #14 /var/lib/jenkins/workspace/example-tests/vendor/behat/behat/src/Behat/Behat/Tester/Runtime/RuntimeFeatureTester.php(83): Behat\Behat\EventDispatcher\Tester\EventDispatchingScenarioTester->test(Object(Behat\Behat\Context\Environment\InitializedContextEnvironment), Object(Behat\Gherkin\Node\FeatureNode), Object(Behat\Gherkin\Node\ScenarioNode), false)
      #15 /var/lib/jenkins/workspace/example-tests/vendor/behat/behat/src/Behat/Behat/Hook/Tester/HookableFeatureTester.php(72): Behat\Behat\Tester\Runtime\RuntimeFeatureTester->test(Object(Behat\Behat\Context\Environment\UninitializedContextEnvironment), Object(Behat\Gherkin\Node\FeatureNode), false)
      #16 /var/lib/jenkins/workspace/example-tests/vendor/behat/behat/src/Behat/Behat/EventDispatcher/Tester/EventDispatchingFeatureTester.php(71): Behat\Behat\Hook\Tester\HookableFeatureTester->test(Object(Behat\Behat\Context\Environment\UninitializedContextEnvironment), Object(Behat\Gherkin\Node\FeatureNode), false)
      #17 /var/lib/jenkins/workspace/example-tests/vendor/behat/behat/src/Behat/Testwork/Tester/Runtime/RuntimeSuiteTester.php(63): Behat\Behat\EventDispatcher\Tester\EventDispatchingFeatureTester->test(Object(Behat\Behat\Context\Environment\UninitializedContextEnvironment), Object(Behat\Gherkin\Node\FeatureNode), false)
      #18 /var/lib/jenkins/workspace/example-tests/vendor/behat/behat/src/Behat/Testwork/Hook/Tester/HookableSuiteTester.php(73): Behat\Testwork\Tester\Runtime\RuntimeSuiteTester->test(Object(Behat\Behat\Context\Environment\UninitializedContextEnvironment), Object(Behat\Testwork\Specification\GroupedSpecificationIterator), false)
      #19 /var/lib/jenkins/workspace/example-tests/vendor/behat/behat/src/Behat/Testwork/EventDispatcher/Tester/EventDispatchingSuiteTester.php(72): Behat\Testwork\Hook\Tester\HookableSuiteTester->test(Object(Behat\Behat\Context\Environment\UninitializedContextEnvironment), Object(Behat\Testwork\Specification\GroupedSpecificationIterator), false)
      #20 /var/lib/jenkins/workspace/example-tests/vendor/behat/behat/src/Behat/Testwork/Tester/Runtime/RuntimeExercise.php(71): Behat\Testwork\EventDispatcher\Tester\EventDispatchingSuiteTester->test(Object(Behat\Behat\Context\Environment\UninitializedContextEnvironment), Object(Behat\Testwork\Specification\GroupedSpecificationIterator), false)
      #21 /var/lib/jenkins/workspace/example-tests/vendor/behat/behat/src/Behat/Testwork/EventDispatcher/Tester/EventDispatchingExercise.php(70): Behat\Testwork\Tester\Runtime\RuntimeExercise->test(Array, false)
      #22 /var/lib/jenkins/workspace/example-tests/vendor/behat/behat/src/Behat/Testwork/Ordering/OrderedExercise.php(80): Behat\Testwork\EventDispatcher\Tester\EventDispatchingExercise->test(Array, false)
      #23 /var/lib/jenkins/workspace/example-tests/vendor/behat/behat/src/Behat/Testwork/Tester/Cli/ExerciseController.php(146): Behat\Testwork\Ordering\OrderedExercise->test(Array, false)
      #24 /var/lib/jenkins/workspace/example-tests/vendor/behat/behat/src/Behat/Testwork/Tester/Cli/ExerciseController.php(108): Behat\Testwork\Tester\Cli\ExerciseController->testSpecifications(Object(Symfony\Component\Console\Input\ArgvInput), Array)
      #25 /var/lib/jenkins/workspace/example-tests/vendor/behat/behat/src/Behat/Testwork/Cli/Command.php(63): Behat\Testwork\Tester\Cli\ExerciseController->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
      #26 /var/lib/jenkins/workspace/example-tests/vendor/symfony/console/Command/Command.php(259): Behat\Testwork\Cli\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
      #27 /var/lib/jenkins/workspace/example-tests/vendor/symfony/console/Application.php(841): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
      #28 /var/lib/jenkins/workspace/example-tests/vendor/symfony/console/Application.php(192): Symfony\Component\Console\Application->doRunCommand(Object(Behat\Testwork\Cli\Command), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
      #29 /var/lib/jenkins/workspace/example-tests/vendor/behat/behat/src/Behat/Testwork/Cli/Application.php(121): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
      #30 /var/lib/jenkins/workspace/example-tests/vendor/symfony/console/Application.php(123): Behat\Testwork\Cli\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
      #31 /var/lib/jenkins/workspace/example-tests/vendor/behat/behat/bin/behat(31): Symfony\Component\Console\Application->run()
      #32 {main}
```

I'm seeing some other test failures which I think may be due to Goutte moving too fast, and the page hasn't fully loaded or redirected before Goutte reports and element isn't in place. That's the only thing I can think of that might be at play here. That, and Varnish is in place on the remote dev server and not in the VM locally.

@jhedstrom would it make sense for the login process to use a [spin function](http://docs.behat.org/en/v2.5/cookbook/using_spin_functions.html) somewhere along the way? (Apologies if it does use one and I missed it.)

**Comment by eeeschwartz** [comment]
@kostajh is it possible your issue would be fixed by [this recent commit](https://github.com/jhedstrom/drupalextension/commit/9bff3fd08358d34562f1a94514ced0a573f3cbec#diff-2bd4dd7f9fc081894c12ba45c2fa3762)? 

Before this commit (including version 3.1.5), drupalextension decided if a session was successful [if the logout link was visible](https://github.com/jhedstrom/drupalextension/blob/v3.1.5/src/Drupal/DrupalExtension/Context/RawDrupalContext.php#L454). I've found that certain browsers (phantomjs for me) fail to find the link, even when a session is successful.

You could try updating to master.

**Comment by kwoxer** [comment]
I had the same issue. Just update via composer and all is fine. :)

**Comment by jhedstrom** [comment]
This seems to have resolved itself. Feel free to re-open if not.
